-- DDL QUERIES--
TRUNCATE TABLE EMPLOYE2;
DROP TABLE IF EXISTS EMPLOYE2; 

CREATE TABLE KIPS(
	ID INT,
	NAME VARCHAR(50),
	CLASS VARCHAR(50)
);
ALTER TABLE KIPS
ADD AGE INT CHECK(AGE > 15),
ADD MARKS FLOAT;

-- DML QUERIES--
INSERT INTO KIPS(ID, NAME, CLASS, AGE, MARKS)
VALUES
(101, 'AYESHA','BS-CS',18 , 596),
(107, 'ANUM','BS-ENG',16 , 472),
(105, 'LAIBA','BS-CHE',17 , 583),
(103, 'ANMOL','BS-ZOL',19 , 516),
(108, 'RIDA','BS-MATH',20 , 312),
(102, 'LARAIB','BS-CS',16 , 400);

UPDATE KIPS SET NAME = 'SANIA' WHERE NAME = 'ANUM';
DELETE FROM KIPS WHERE ID = 102;

ALTER TABLE KIPS
DROP COLUMN  IF EXISTS AGE;
TRUNCATE TABLE KIPS;

ALTER TABLE KIPS
ADD CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


--DQL QUERY--
SELECT * FROM KIPS
SELECT * FROM KIPS ORDER BY ID ASC;


ALTER TABLE KIPS
RENAME COLUMN TOTAL_MARKS TO TOTALMARKS;

ALTER TABLE KIPS
ALTER COLUMN AGE TYPE SMALLINT;

ALTER TABLE KIPS
ALTER COLUMN CLASS SET NOT NULL;

ALTER TABLE KIPS
ADD CONSTRAINT totalmarks_check CHECK (TOTALMARKS > 200);

